### ISSUE TITLE
Gh pages displays README

### ISSUE THREAD

**Issue by Quantum-Codes** [SparkScratch-P/CatSight-AI#1]
Github pages at [sparkscratch-p.github.io/catsight-ai](https://sparkscratch-p.github.io/CatSight-AI/) should display stuff in the web folder. Seems like it is set to /root

**Comment by SparkScratch-P** [comment]
yeah actually, if u see many of my projects, gh pages displays readme. This is because, i don't have any index.html or .md file... so, the second choice is, the readme.  I am not getting time, Durga Puja nah, from 1st, so, busy .... thn I have a trip and once I am back, I will write the entire readme, tht can be read there too , but it looks good as the webpage too, like the main web page for the project!

**Comment by SparkScratch-P** [comment]
But ofc, u can try out the project here: https://sparkscratch-p.github.io/CatSight-AI/web/

**Comment by Quantum-Codes** [comment]
Oh okay, didn't know I could access like that
